services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: manoel
      POSTGRES_PASSWORD: juniorssj
      POSTGRES_DB: fintracker