spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/fintracker
spring.datasource.username=manoel
spring.datasource.password=juniorssj

spring.jpa.hibernate.ddl-auto=update